module.exports = [
    {
      id: 132,
      firstName: 'Van A',
      lastName: 'Nguyen',
      username: 'name1',
      password: '123456',
      email: 'name1@omnicasa.com',
      address: '01 Phan Thuc Duyet street, Tan Binh dist.',
      phoneNumber: '012212124566',
    },
    {
      id: 112,
      firstName: 'Van B',
      lastName: 'Tran',
      username: 'name2',
      password: '123456',
      email: 'name2@omnicasa.com',
      address: '01 Cuu Long street, Tan Binh dist.',
      phoneNumber: '012212124566',
    },    
    {
      id: 710,
      firstName: 'La',
      lastName: 'La',
      password: '123456',
      email: 'name3@omnicasa.com',
      username: 'name3',
      address: '01 Bach Dang street, Tan Binh dist.',
      phoneNumber: '012212124566',
    },
    {
      id: 719,
      firstName: 'La',
      lastName: 'La',
      password: '123456',
      email: 'name3@omnicasa.com',
      username: 'name3',
      address: '01 Bach Dang street, Tan Binh dist.',
      phoneNumber: '012212124566',
    },
    {
      id: 718,
      firstName: 'La',
      lastName: 'La',
      password: '123456',
      email: 'name3@omnicasa.com',
      username: 'name3',
      address: '01 Bach Dang street, Tan Binh dist.',
      phoneNumber: '012212124566',
    }
  ]