export const FETCH_USERS = 'users/FETCH_USERS'
export const SET_USERS = 'users/SET_USERS'
export const GET_USERS = 'users/GET_USERS'
export const ADD_USER = 'users/ADD_USER'
export const UPDATE_USER = 'users/UPDATE_USER'
export const DELETE_USER = 'users/DELETE_USER'